package com.example.hydrant.repository

import com.example.hydrant.model.FireHydrant
import com.google.firebase.database.DataSnapshot
import com.google.firebase.database.DatabaseError
import com.google.firebase.database.FirebaseDatabase
import com.google.firebase.database.ValueEventListener
import com.google.firebase.database.getValue
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

class FireHydrantRepository {
    // Use your Asia region database URL
    private val database = FirebaseDatabase.getInstance("https://firegrid-58bc3-default-rtdb.asia-southeast1.firebasedatabase.app/")
    private val hydrantsRef = database.getReference("fire_hydrants")

    /**
     * Helper function to extract numeric ID from hydrant ID string.
     * Handles formats like "Id_1", "Id_01", "Id_001", etc.
     */
    private fun extractHydrantNumber(hydrantId: String): Int {
        return try {
            val numberPart = hydrantId.removePrefix("Id_").trim()
            numberPart.toIntOrNull() ?: 0
        } catch (e: Exception) {
            0
        }
    }

    /**
     * Generates a zero-padded ID like Id_01, Id_02, ... Id_10, Id_99, Id_100
     * Uses 2 digits for 1-99, 3 digits for 100-999, etc.
     */
    private fun generateZeroPaddedId(number: Int): String {
        return when {
            number < 100 -> "Id_${number.toString().padStart(2, '0')}"   // Id_01 to Id_99
            number < 1000 -> "Id_${number.toString().padStart(3, '0')}"  // Id_100 to Id_999
            else -> "Id_${number.toString().padStart(4, '0')}"           // Id_1000+
        }
    }

    /**
     * Generates a formatted timestamp string like "January 10, 2026 at 3:33:09 PM UTC+8"
     */
    private fun getFormattedTimestamp(): String {
        val dateFormat = SimpleDateFormat("MMMM dd, yyyy 'at' h:mm:ss a 'UTC+8'", Locale.ENGLISH)
        dateFormat.timeZone = TimeZone.getTimeZone("Asia/Manila") // UTC+8
        return dateFormat.format(Date())
    }

    // Add a new fire hydrant with zero-padded ID: Id_01, Id_02, etc.
    // Hydrant name is auto-generated as "Hydrant Id_01"
    suspend fun addFireHydrant(hydrant: FireHydrant): Result<String> {
        return try {
            val municipalityRef = hydrantsRef.child(hydrant.municipality)

            // Get current snapshot to find the highest existing ID
            val snapshot = municipalityRef.get().await()

            // Find the highest existing ID number
            var maxIdNumber = 0
            if (snapshot.exists()) {
                for (childSnapshot in snapshot.children) {
                    val docId = childSnapshot.key ?: continue
                    val idNumber = extractHydrantNumber(docId)
                    if (idNumber > maxIdNumber) {
                        maxIdNumber = idNumber
                    }
                }
            }

            // Next ID is max + 1 with zero-padding
            val nextIdNumber = maxIdNumber + 1
            val newId = generateZeroPaddedId(nextIdNumber)

            // Auto-generate hydrant name based on zero-padded ID
            val autoGeneratedName = "Hydrant $newId"

            // Get formatted timestamp
            val formattedTimestamp = getFormattedTimestamp()

            // Create hydrant with zero-padded ID, auto-generated name, and formatted timestamp
            val hydrantWithId = hydrant.copy(
                id = newId,
                hydrantName = autoGeneratedName,
                lastUpdated = formattedTimestamp
            )
            municipalityRef.child(newId).setValue(hydrantWithId).await()

            Result.success(newId)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    // Get all fire hydrants for a specific municipality
    fun getHydrantsByMunicipality(municipality: String): Flow<List<FireHydrant>> = callbackFlow {
        val municipalityRef = hydrantsRef.child(municipality)

        val listener = object : ValueEventListener {
            override fun onDataChange(snapshot: DataSnapshot) {
                val hydrants = mutableListOf<FireHydrant>()
                for (child in snapshot.children) {
                    val hydrant = child.getValue<FireHydrant>()
                    if (hydrant != null) {
                        hydrants.add(hydrant)
                    }
                }
                // Sort numerically before sending
                val sortedHydrants = hydrants.sortedBy { extractHydrantNumber(it.id) }
                trySend(sortedHydrants)
            }

            override fun onCancelled(error: DatabaseError) {
                close(error.toException())
            }
        }

        municipalityRef.addValueEventListener(listener)
        awaitClose { municipalityRef.removeEventListener(listener) }
    }

    // Get hydrant counts for a municipality
    fun getHydrantCounts(municipality: String): Flow<Pair<Int, Int>> = callbackFlow {
        val municipalityRef = hydrantsRef.child(municipality)

        val listener = object : ValueEventListener {
            override fun onDataChange(snapshot: DataSnapshot) {
                var inService = 0
                var outOfService = 0

                for (child in snapshot.children) {
                    val hydrant = child.getValue<FireHydrant>()
                    when (hydrant?.serviceStatus) {
                        "In Service" -> inService++
                        "Out of Service" -> outOfService++
                    }
                }
                trySend(Pair(inService, outOfService))
            }

            override fun onCancelled(error: DatabaseError) {
                close(error.toException())
            }
        }

        municipalityRef.addValueEventListener(listener)
        awaitClose { municipalityRef.removeEventListener(listener) }
    }

    // Update an existing fire hydrant
    suspend fun updateFireHydrant(hydrant: FireHydrant): Result<Unit> {
        return try {
            // Update the lastUpdated timestamp when editing
            val formattedTimestamp = getFormattedTimestamp()
            val updatedHydrant = hydrant.copy(lastUpdated = formattedTimestamp)

            hydrantsRef.child(updatedHydrant.municipality)
                .child(updatedHydrant.id)
                .setValue(updatedHydrant)
                .await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    // Delete a fire hydrant
    suspend fun deleteFireHydrant(municipality: String, hydrantId: String): Result<Unit> {
        return try {
            hydrantsRef.child(municipality)
                .child(hydrantId)
                .removeValue()
                .await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}