package com.example.hydrant.repository

import com.example.hydrant.model.FireHydrant
import com.google.firebase.database.DataSnapshot
import com.google.firebase.database.DatabaseError
import com.google.firebase.database.FirebaseDatabase
import com.google.firebase.database.ValueEventListener
import com.google.firebase.database.getValue
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

class FireHydrantRepository {
    // Use your Asia region database URL
    private val database = FirebaseDatabase.getInstance("https://firegrid-58bc3-default-rtdb.asia-southeast1.firebasedatabase.app/")
    private val hydrantsRef = database.getReference("fire_hydrants")

    // Add a new fire hydrant with custom ID: Id_1, Id_2, etc.
    // Hydrant name is auto-generated as "Hydrant Id_X"
    suspend fun addFireHydrant(hydrant: FireHydrant): Result<String> {
        return try {
            val municipalityRef = hydrantsRef.child(hydrant.municipality)

            // Get current snapshot to find the highest existing ID
            val snapshot = municipalityRef.get().await()

            // Find the highest existing ID number
            var maxIdNumber = 0
            if (snapshot.exists()) {
                for (childSnapshot in snapshot.children) {
                    val docId = childSnapshot.key ?: continue
                    val idNumStr = docId.removePrefix("Id_")
                    val idNumber = idNumStr.toIntOrNull()
                    if (idNumber != null && idNumber > maxIdNumber) {
                        maxIdNumber = idNumber
                    }
                }
            }

            // Next ID is max + 1
            val nextIdNumber = maxIdNumber + 1
            val newId = "Id_$nextIdNumber"

            // Auto-generate hydrant name based on ID
            val autoGeneratedName = "Hydrant Id_$nextIdNumber"

            // Create hydrant with custom ID and auto-generated name
            val hydrantWithId = hydrant.copy(
                id = newId,
                hydrantName = autoGeneratedName
            )
            municipalityRef.child(newId).setValue(hydrantWithId).await()

            Result.success(newId)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    // Get all fire hydrants for a specific municipality
    fun getHydrantsByMunicipality(municipality: String): Flow<List<FireHydrant>> = callbackFlow {
        val municipalityRef = hydrantsRef.child(municipality)

        val listener = object : ValueEventListener {
            override fun onDataChange(snapshot: DataSnapshot) {
                val hydrants = mutableListOf<FireHydrant>()
                for (child in snapshot.children) {
                    val hydrant = child.getValue<FireHydrant>()
                    if (hydrant != null) {
                        hydrants.add(hydrant)
                    }
                }
                trySend(hydrants)
            }

            override fun onCancelled(error: DatabaseError) {
                close(error.toException())
            }
        }

        municipalityRef.addValueEventListener(listener)
        awaitClose { municipalityRef.removeEventListener(listener) }
    }

    // Get hydrant counts for a municipality
    fun getHydrantCounts(municipality: String): Flow<Pair<Int, Int>> = callbackFlow {
        val municipalityRef = hydrantsRef.child(municipality)

        val listener = object : ValueEventListener {
            override fun onDataChange(snapshot: DataSnapshot) {
                var inService = 0
                var outOfService = 0

                for (child in snapshot.children) {
                    val hydrant = child.getValue<FireHydrant>()
                    when (hydrant?.serviceStatus) {
                        "In Service" -> inService++
                        "Out of Service" -> outOfService++
                    }
                }
                trySend(Pair(inService, outOfService))
            }

            override fun onCancelled(error: DatabaseError) {
                close(error.toException())
            }
        }

        municipalityRef.addValueEventListener(listener)
        awaitClose { municipalityRef.removeEventListener(listener) }
    }

    // Update an existing fire hydrant
    suspend fun updateFireHydrant(hydrant: FireHydrant): Result<Unit> {
        return try {
            hydrantsRef.child(hydrant.municipality)
                .child(hydrant.id)
                .setValue(hydrant)
                .await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    // Delete a fire hydrant
    suspend fun deleteFireHydrant(municipality: String, hydrantId: String): Result<Unit> {
        return try {
            hydrantsRef.child(municipality)
                .child(hydrantId)
                .removeValue()
                .await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}